# @package _global_
defaults:
  - _self_

openai_api_base:
openai_api_key:
model_name:
max_context_length: 8192
exllama: False

system_tag_start: "<|im_start|>system\\n"
system_tag_end: "<|im_end|>\\n"

user_tag_start: "<|im_start|>system\\n"
user_tag_end: "<|im_end|>\\n"

ai_tag_start: "<|im_start|>assistant\\n"
ai_tag_end: "<|im_end|>"

stop_words:
 - "<|im_end|>"
